var expect = require("chai").expect;

var temp = require('temp');
var path = require('path');

var utils = require('../lib/utils');
var site = require('../lib/site');
var fs = require('fs');

var srcPrefix = path.join('test', 'sites');
var compPrefix = path.join('test', 'correct-sites');

// compare all the files generated by site.build against
// a set of known correct ones
function compareAllGeneratedFiles(folder) {
  var destPath = path.join("temp", folder);
  utils.ensureDirectoryExists("temp");
  utils.ensureDirectoryExists(destPath);

  var srcPath = path.join(srcPrefix, folder);
  var compPath = path.join(compPrefix, folder);

  site.build(srcPath, destPath, function (uriPath) {
    // read the file generated by site
    var generated = fs.readFileSync(path.join(destPath, uriPath), 'utf8');
    var correct = fs.readFileSync(path.join(compPath, uriPath), 'utf8');
    expect(generated.trim()).to.equal(correct.trim());
  });
}

describe("site", function() {
  it('local-variables', () => {
    compareAllGeneratedFiles('local-variables');
  });

  it('check imbue-site', () => {
    compareAllGeneratedFiles('imbue-site');
  });

  it('check nested-layout', () => {
    compareAllGeneratedFiles('nested-layout');
  });

  it('check jaded-1', () => {
    compareAllGeneratedFiles('jaded-1');
  });

  it('check in-list', () => {
    compareAllGeneratedFiles('in-list');
  });
});
